project_id = "kzubwatryfgonzuzldej"

[global.env]
AZURE_COGNITIVE_KEY = "AZURE_COGNITIVE_KEY"
AZURE_COGNITIVE_ENDPOINT = "AZURE_COGNITIVE_ENDPOINT"
AZURE_SPEECH_KEY = "AZURE_SPEECH_KEY"
AZURE_SPEECH_ENDPOINT = "AZURE_SPEECH_ENDPOINT"
AZURE_VISION_KEY = "AZURE_VISION_KEY"
AZURE_VISION_ENDPOINT = "AZURE_VISION_ENDPOINT"

[[functions]]
name = "test-azure"
verify_jwt = false