// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzubwatryfgonzuzldej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6dWJ3YXRyeWZnb256dXpsZGVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxMjk0ODgsImV4cCI6MjA1MjcwNTQ4OH0.qH6jt-tvZsC114SnfXQR0KPq2wVua2pSuoBc70tPuz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);