project_id = "kzubwatryfgonzuzldej"
AZURE_OPENAI_API_KEY = "AZURE_OPENAI_API_KEY"
AZURE_OPENAI_ENDPOINT = "AZURE_OPENAI_ENDPOINT"
AZURE_SPEECH_KEY = "AZURE_SPEECH_KEY"
AZURE_SPEECH_ENDPOINT = "AZURE_SPEECH_ENDPOINT"